# Exploring Disney Land Wait Time Data Set

In [1]:
import pandas as pd ## call pandas functions using "pd"
import numpy as np  ## call numpy functions using "np"

#import meta data
meta = pd.read_csv("disney.csv")

#import magic kingdom rides (wait times)
splash = pd.read_csv("splash_mountain.csv")
seven_dwarfs = pd.read_csv("7_dwarfs_train.csv")
pirates = pd.read_csv('pirates_of_caribbean.csv')

In [2]:
# First five rows of meta, five columns, # start date 2012
meta.iloc[0:5, 0:10]

,DATE,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,HOLIDAYM
0,01/01/2012,NaN,1,0,1,1,2012,CHRISTMAS PEAK,0,5
1,01/02/2012,NaN,2,1,1,1,2012,CHRISTMAS,2,5
2,01/03/2012,NaN,3,2,1,1,2012,CHRISTMAS,3,0
3,01/04/2012,NaN,4,3,1,1,2012,CHRISTMAS,4,0
4,01/05/2012,NaN,5,4,1,1,2012,CHRISTMAS,5,0

In [4]:
# Dropping sactmin from magic world rides, then dropping NaN from spostmin

# Drop rows where wait time is not available (-999)
pirates = pirates[pirates.SPOSTMIN > 0]
seven_dwarfs = seven_dwarfs[seven_dwarfs.SPOSTMIN > 0]
splash = splash[splash.SPOSTMIN > 0]

splash.head() #has posted minutes for each ride

         date             datetime  SPOSTMIN  SACTMIN
0  01/01/2012  2012-01-01 10:31:00      30.0      NaN
1  01/01/2012  2012-01-01 10:40:00      30.0      NaN
3  01/01/2012  2012-01-01 12:02:00      30.0      NaN
5  01/01/2012  2012-01-01 12:38:00      35.0      NaN
6  01/01/2012  2012-01-01 12:44:00      25.0      NaN

In [5]:
#Merging each ride with meta_data, using date as key
meta_splash = pd.merge(splash, meta, left_on="date", right_on="DATE").drop('DATE', axis = 1)

In [ ]:
#skip run due to crashing for now
#meta_dwarfs = pd.merge(seven_dwarfs, meta, left_on="date", right_on="DATE").drop('DATE', axis = 1)
#meta_pirates = pd.merge(pirates, meta, left_on="date", right_on="DATE").drop('DATE', axis = 1)

In [6]:
#change NAs to 0 values
meta_splash = meta_splash.fillna(0)
#format date in a way that can be worked with
meta_splash['date'] = pd.to_datetime(meta_splash['date'])
meta_splash.head()

,date,datetime,SPOSTMIN,SACTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
0,2012-01-01,2012-01-01 10:31:00,30.0,0.0,0,1,0,1,1,2012,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
1,2012-01-01,2012-01-01 10:40:00,30.0,0.0,0,1,0,1,1,2012,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
2,2012-01-01,2012-01-01 12:02:00,30.0,0.0,0,1,0,1,1,2012,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
3,2012-01-01,2012-01-01 12:38:00,35.0,0.0,0,1,0,1,1,2012,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
4,2012-01-01,2012-01-01 12:44:00,25.0,0.0,0,1,0,1,1,2012,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0

In [7]:
#sum all posted wait times by day in meta_splash
sum_by_day = meta_splash.groupby('date')['SPOSTMIN'].sum()
#reset index to create dataframe columns
sum_by_day = sum_by_day.reset_index()
sum_by_day = pd.DataFrame(sum_by_day,columns=['date','SPOSTMIN'])
sum_by_day.head()

        date  SPOSTMIN
0 2012-01-01     415.0
1 2012-01-02     350.0
2 2012-01-03      10.0
3 2012-01-04     120.0
4 2012-01-05     535.0

In [15]:
#compute weighted average of posted wait times by day
avg = sum_by_day.groupby('date')['SPOSTMIN'].mean()
#reset index to create dataframe columns
avg = avg.reset_index()
#name columns of df
avg = pd.DataFrame(avg,columns=['date','SPOSTMIN'])
avg.head()

date        datetime64[ns]
SPOSTMIN           float64
dtype: object

In [23]:
meta['DATE'] = pd.to_datetime(meta['DATE'])
#merge back with original meta set for daily weighted averages
meta_splash2 = pd.merge(avg, meta, left_on="date", right_on="DATE").drop('DATE', axis = 1)
meta_splash2.head()

,date,SPOSTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
0,2012-01-01,415.0,NaN,1,0,1,1,2012,CHRISTMAS PEAK,0,...,1,1,15:45,NaN,Mickey's Jingle Jungle Parade,NaN,0,NaN,NaN,NaN
1,2012-01-02,350.0,NaN,2,1,1,1,2012,CHRISTMAS,2,...,1,1,15:45,NaN,Mickey's Jingle Jungle Parade,NaN,0,NaN,NaN,NaN
2,2012-01-03,10.0,NaN,3,2,1,1,2012,CHRISTMAS,3,...,1,1,15:45,NaN,Mickey's Jammin' Jungle Parade,NaN,0,NaN,NaN,NaN
3,2012-01-04,120.0,NaN,4,3,1,1,2012,CHRISTMAS,4,...,1,1,15:45,NaN,Mickey's Jammin' Jungle Parade,NaN,0,NaN,NaN,NaN
4,2012-01-05,535.0,NaN,5,4,1,1,2012,CHRISTMAS,5,...,1,1,15:45,NaN,Mickey's Jammin' Jungle Parade,NaN,0,NaN,NaN,NaN

In [31]:
#fill na for new meta splash data
meta_splash2 = meta_splash2.fillna(0)

In [32]:
xmas = meta_splash2[meta_splash2.SEASON == 'CHRISTMAS']
xmas

,date,SPOSTMIN,WDW_TICKET_SEASON,DAYOFWEEK,DAYOFYEAR,WEEKOFYEAR,MONTHOFYEAR,YEAR,SEASON,HOLIDAYPX,...,HSFIREWKS,AKPRDDAY,AKPRDDT1,AKPRDDT2,AKPRDDN,AKFIREN,AKSHWNGT,AKSHWNT1,AKSHWNT2,AKSHWNN
1,2012-01-02,350.0,0,2,1,1,1,2012,CHRISTMAS,2,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
2,2012-01-03,10.0,0,3,2,1,1,2012,CHRISTMAS,3,...,1,1,15:45,0.0,Mickey's Jammin' Jungle Parade,0.0,0,0,0,0
3,2012-01-04,120.0,0,4,3,1,1,2012,CHRISTMAS,4,...,1,1,15:45,0.0,Mickey's Jammin' Jungle Parade,0.0,0,0,0,0
4,2012-01-05,535.0,0,5,4,1,1,2012,CHRISTMAS,5,...,1,1,15:45,0.0,Mickey's Jammin' Jungle Parade,0.0,0,0,0,0
5,2012-01-06,565.0,0,6,5,1,1,2012,CHRISTMAS,6,...,1,1,15:45,0.0,Mickey's Jammin' Jungle Parade,0.0,0,0,0,0
6,2012-01-07,205.0,0,7,6,1,1,2012,CHRISTMAS,7,...,1,1,15:45,0.0,Mickey's Jammin' Jungle Parade,0.0,0,0,0,0
7,2012-01-08,415.0,0,1,7,2,1,2012,CHRISTMAS,8,...,1,1,15:45,0.0,Mickey's Jammin' Jungle Parade,0.0,0,0,0,0
8,2012-01-09,535.0,0,2,8,2,1,2012,CHRISTMAS,8,...,1,1,15:45,0.0,Mickey's Jammin' Jungle Parade,0.0,0,0,0,0
348,2012-12-18,610.0,0,3,352,51,12,2012,CHRISTMAS,7,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
349,2012-12-19,1615.0,0,4,353,51,12,2012,CHRISTMAS,6,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
350,2012-12-20,1075.0,0,5,354,51,12,2012,CHRISTMAS,5,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
351,2012-12-21,525.0,0,6,355,51,12,2012,CHRISTMAS,4,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
352,2012-12-22,665.0,0,7,356,51,12,2012,CHRISTMAS,3,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
353,2012-12-23,1065.0,0,1,357,52,12,2012,CHRISTMAS,2,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
354,2012-12-24,3225.0,0,2,358,52,12,2012,CHRISTMAS,0,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
355,2012-12-25,3200.0,0,3,359,52,12,2012,CHRISTMAS,0,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
356,2012-12-26,1800.0,0,4,360,52,12,2012,CHRISTMAS,2,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
636,2013-12-18,2010.0,0,4,351,50,12,2013,CHRISTMAS,7,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
637,2013-12-19,2085.0,0,5,352,50,12,2013,CHRISTMAS,6,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
638,2013-12-20,1595.0,0,6,353,50,12,2013,CHRISTMAS,5,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
639,2013-12-21,4805.0,0,7,354,50,12,2013,CHRISTMAS,4,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
640,2013-12-22,4850.0,0,1,355,51,12,2013,CHRISTMAS,3,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
641,2013-12-23,5165.0,0,2,356,51,12,2013,CHRISTMAS,2,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
642,2013-12-24,4750.0,0,3,357,51,12,2013,CHRISTMAS,0,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
643,2013-12-25,6820.0,0,4,358,51,12,2013,CHRISTMAS,0,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
644,2013-12-26,6350.0,0,5,359,51,12,2013,CHRISTMAS,2,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
651,2014-01-02,4910.0,0,5,1,0,1,2014,CHRISTMAS,2,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
652,2014-01-03,2180.0,0,6,2,0,1,2014,CHRISTMAS,3,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
653,2014-01-04,3380.0,0,7,3,0,1,2014,CHRISTMAS,4,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
654,2014-01-05,5465.0,0,1,4,1,1,2014,CHRISTMAS,5,...,1,1,15:45,0.0,Mickey's Jingle Jungle Parade,0.0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909,2017-12-20,9125.0,regular,4,353,51,12,2017,CHRISTMAS,5,...,1,0,0,0.0,0,0.0,2,19:15,20:30,Rivers of Light
1910,2017-12-21,4130.0,peak,5,354,51,12,2017,CHRISTMAS,4,...,1,0,0,0.0,0,0.0,2,19:15,20:30,Rivers of Light
1911,2017-12-22,3670.0,peak,6,355,51,12,2017,CHRISTMAS,3,...,1,0,0,0.0,0,0.0,2,19:15,20:30,Rivers of Light
1912,2017-12-23,6780.0,peak,7,356,51,12,2017,CHRISTMAS,2,...,1,0,0,0.0,0,0.0,2,19:15,20:30,Rivers of Light
1913,2017-12-24,10195.0,peak,1,357,52,12,2017,CHRISTMAS,0,...,1,0,0,0.0,0,0.0,3,19:15,20:30,Rivers of Light
1914,2017-12-25,9390.0,peak,2,358,52,12,2017,CHRISTMAS,0,...,1,0,0,0.0,0,0.0,3,19:15,20:30,Rivers of Light
1915,2017-12-26,6720.0,peak,3,359,52,12,2017,CHRISTMAS,2,...,1,0,0,0.0,0,0.0,3,19:15,20:30,Rivers of Light
1922,2018-01-02,2485.0,peak,3,1,0,1,2018,CHRISTMAS,2,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
1923,2018-01-03,1295.0,peak,4,2,0,1,2018,CHRISTMAS,3,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
1924,2018-01-04,3655.0,regular,5,3,0,1,2018,CHRISTMAS,4,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
1925,2018-01-05,2035.0,regular,6,4,0,1,2018,CHRISTMAS,5,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
1926,2018-01-06,1690.0,regular,7,5,0,1,2018,CHRISTMAS,6,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
1927,2018-01-07,2995.0,regular,1,6,1,1,2018,CHRISTMAS,7,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
2247,2018-12-18,2490.0,regular,3,351,50,12,2018,CHRISTMAS,7,...,1,0,0,0.0,0,0.0,2,18:15,19:30,Rivers of Light
2248,2018-12-19,6340.0,regular,4,352,50,12,2018,CHRISTMAS,6,...,1,0,0,0.0,0,0.0,2,18:15,19:30,Rivers of Light
2249,2018-12-20,635.0,peak,5,353,50,12,2018,CHRISTMAS,5,...,1,0,0,0.0,0,0.0,2,18:15,19:30,Rivers of Light
2250,2018-12-21,1130.0,peak,6,354,50,12,2018,CHRISTMAS,4,...,1,0,0,0.0,0,0.0,2,18:15,19:30,Rivers of Light
2251,2018-12-22,3945.0,peak,7,355,50,12,2018,CHRISTMAS,3,...,1,0,0,0.0,0,0.0,2,18:15,19:30,Rivers of Light
2252,2018-12-23,3820.0,peak,1,356,51,12,2018,CHRISTMAS,2,...,1,0,0,0.0,0,0.0,3,18:15,19:45,Rivers of Light
2253,2018-12-24,7690.0,peak,2,357,51,12,2018,CHRISTMAS,0,...,1,0,0,0.0,0,0.0,3,18:15,19:45,Rivers of Light
2254,2018-12-25,10345.0,peak,3,358,51,12,2018,CHRISTMAS,0,...,1,0,0,0.0,0,0.0,3,18:15,19:45,Rivers of Light
2255,2018-12-26,7775.0,peak,4,359,51,12,2018,CHRISTMAS,2,...,1,0,0,0.0,0,0.0,3,18:15,19:45,Rivers of Light
2262,2019-01-02,12595.0,peak,4,1,0,1,2019,CHRISTMAS,2,...,1,0,0,0.0,0,0.0,2,18:30,20:00,Rivers of Light
2263,2019-01-03,13090.0,peak,5,2,0,1,2019,CHRISTMAS,3,...,1,0,0,0.0,0,0.0,2,18:30,20:00,Rivers of Light
2264,2019-01-04,10845.0,peak,6,3,0,1,2019,CHRISTMAS,4,...,1,0,0,0.0,0,0.0,2,18:30,20:00,Rivers of Light
2265,2019-01-05,5375.0,peak,7,4,0,1,2019,CHRISTMAS,5,...,1,0,0,0.0,0,0.0,2,18:30,20:00,Rivers of Light
2266,2019-01-06,3535.0,regular,1,5,1,1,2019,CHRISTMAS,6,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
2267,2019-01-07,3895.0,regular,2,6,1,1,2019,CHRISTMAS,7,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light
2268,2019-01-08,4245.0,value,3,7,1,1,2019,CHRISTMAS,8,...,1,0,0,0.0,0,0.0,3,18:30,19:45,Rivers of Light
2269,2019-01-09,2880.0,value,4,8,1,1,2019,CHRISTMAS,9,...,1,0,0,0.0,0,0.0,2,18:30,19:45,Rivers of Light